Resources:
    AttemptsTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: ${self:custom.attemptsTableName}
            AttributeDefinitions:
                - AttributeName: userId
                  AttributeType: S
                - AttributeName: attemptId
                  AttributeType: S
            KeySchema:
                - AttributeName: userId
                  KeyType: HASH
                - AttributeName: attemptId
                  KeyType: RANGE
            # Set the capacity based on the stage
            ProvisionedThroughput:
                ReadCapacityUnits: ${self:custom.tableThroughput}
                WriteCapacityUnits: ${self:custom.tableThroughput}
    ProjectsTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: ${self:custom.projectsTableName}
            AttributeDefinitions:
                - AttributeName: project
                  AttributeType: S
            KeySchema:
                - AttributeName: project
                  KeyType: HASH
            ProvisionedThroughput:
                ReadCapacityUnits: ${self:custom.tableThroughput}
                WriteCapacityUnits: ${self:custom.tableThroughput}
    UsersTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: ${self:custom.usersTableName}
            AttributeDefinitions:
                - AttributeName: email
                  AttributeType: S
                - AttributeName: projectId
                  AttributeType: S
            KeySchema:
                - AttributeName: email
                  KeyType: HASH
                - AttributeName: projectId
                  KeyType: RANGE
            ProvisionedThroughput:
                ReadCapacityUnits: ${self:custom.tableThroughput}
                WriteCapacityUnits: ${self:custom.tableThroughput}